// export const EQUITY_INVESTMENT_LIST_REQUEST = 'EQUITY_INVESTMENT_LIST_REQUEST';
// export const EQUITY_INVESTMENT_LIST_SUCCESS = 'EQUITY_INVESTMENT_LIST_SUCCESS';
// export const EQUITY_INVESTMENT_LIST_FAIL = 'EQUITY_INVESTMENT_LIST_FAIL';

export const EQUITY_INVESTMENT_STAT_REQUEST = 'EQUITY_INVESTMENT_STAT_REQUEST';
export const EQUITY_INVESTMENT_STAT_SUCCESS = 'EQUITY_INVESTMENT_STAT_SUCCESS';
export const EQUITY_INVESTMENT_STAT_FAIL = 'EQUITY_INVESTMENT_STAT_FAIL';