// export const EQUITY_INVESTMENT_LIST_REQUEST = 'EQUITY_INVESTMENT_LIST_REQUEST';
// export const EQUITY_INVESTMENT_LIST_SUCCESS = 'EQUITY_INVESTMENT_LIST_SUCCESS';
// export const EQUITY_INVESTMENT_LIST_FAIL = 'EQUITY_INVESTMENT_LIST_FAIL';

export const EQUITY_INVESTMENT_STAT_REQUEST = 'EQUITY_INVESTMENT_STAT_REQUEST';
export const EQUITY_INVESTMENT_STAT_SUCCESS = 'EQUITY_INVESTMENT_STAT_SUCCESS';
export const EQUITY_INVESTMENT_STAT_FAIL = 'EQUITY_INVESTMENT_STAT_FAIL';

export const ADMIN_SETTINGS_SUCCESS ='ADMIN_SETTINGS_SUCCESS';
export const ADMIN_SETTINGS_REQUEST = 'ADMIN_SETTINGS_REQUEST'; 
export const ADMIN_SETTINGS_FAIL = 'ADMIN_SETTINGS_FAIL';

export const ADMIN_SETTINGS_REWARD_UPDATE_FAIL = 'ADMIN_SETTINGS_REWARD_UPDATE_FAIL'
export const ADMIN_SETTINGS_REWARD_UPDATE_SUCCESS = 'ADMIN_SETTINGS_REWARD_UPDATE_SUCCESS'