// export const EQUITY_INVESTMENT_LIST_REQUEST = 'EQUITY_INVESTMENT_LIST_REQUEST';
// export const EQUITY_INVESTMENT_LIST_SUCCESS = 'EQUITY_INVESTMENT_LIST_SUCCESS';
// export const EQUITY_INVESTMENT_LIST_FAIL = 'EQUITY_INVESTMENT_LIST_FAIL';

export const EQUITY_INVESTMENT_STAT_REQUEST = 'EQUITY_INVESTMENT_STAT_REQUEST';
export const EQUITY_INVESTMENT_STAT_SUCCESS = 'EQUITY_INVESTMENT_STAT_SUCCESS';
export const EQUITY_INVESTMENT_STAT_FAIL = 'EQUITY_INVESTMENT_STAT_FAIL';

export const EQUITY_INVESTMENT_DATA_REQUEST = 'EQUITY_INVESTMENT_DATA_REQUEST';
export const EQUITY_INVESTMENT_DATA_SUCCESS = 'EQUITY_INVESTMENT_DATA_SUCCESS';
export const EQUITY_INVESTMENT_DATA_FAIL = 'EQUITY_INVESTMENT_DATA_FAIL';

export const ADMIN_SETTINGS_SUCCESS ='ADMIN_SETTINGS_SUCCESS';
export const ADMIN_SETTINGS_REQUEST = 'ADMIN_SETTINGS_REQUEST'; 
export const ADMIN_SETTINGS_FAIL = 'ADMIN_SETTINGS_FAIL';

export const ADMIN_SETTINGS_REWARD_UPDATE_FAIL = 'ADMIN_SETTINGS_REWARD_UPDATE_FAIL'
export const ADMIN_SETTINGS_REWARD_UPDATE_SUCCESS = 'ADMIN_SETTINGS_REWARD_UPDATE_SUCCESS'


export const INVESTMENTS_LIST_REQUEST = 'INVESTMENTS_LIST_REQUEST';
export const INVESTMENTS_LIST_SUCCESS = 'INVESTMENTS_LIST_SUCCESS';
export const INVESTMENTS_LIST_FAIL = 'INVESTMENTS_LIST_FAIL';

export const INVESTMENTS_DETAIL_REQUEST = 'INVESTMENTS_DETAIL_REQUEST';
export const INVESTMENTS_DETAIL_SUCCESS = 'INVESTMENTS_DETAIL_SUCCESS';
export const INVESTMENTS_DETAIL_FAIL = 'INVESTMENTS_DETAIL_FAIL';
export const INVESTMENTS_DETAIL_RESET = 'INVESTMENTS_DETAIL_RESET';


export const INVESTMENTS_TYPE_LIST_REQUEST = 'INVESTMENTS_TYPE_LIST_REQUEST';
export const INVESTMENTS_TYPE_LIST_SUCCESS = 'INVESTMENTS_TYPE_LIST_SUCCESS';
export const INVESTMENTS_TYPE_LIST_FAIL = 'INVESTMENTS_TYPE_LIST_FAIL';