
export const LAND_TITLE_LIST_REQUEST = 'LAND_TITLE_LIST_REQUEST';
export const LAND_TITLE_LIST_SUCCESS = 'LAND_TITLE_LIST_SUCCESS';
export const LAND_TITLE_LIST_FAIL = 'LAND_TITLE_LIST_FAIL';


export const BUILDING_TYPE_LIST_REQUEST = 'BUILDING_TYPE_LIST_REQUEST';
export const BUILDING_TYPE_LIST_SUCCESS = 'BUILDING_TYPE_LIST_SUCCESS';
export const BUILDING_TYPE_LIST_FAIL = 'BUILDING_TYPE_LIST_FAIL';

export const PROJECT_CATEGORY_LIST_REQUEST = 'PROJECT_CATEGORY_LIST_REQUEST';
export const PROJECT_CATEGORY_LIST_SUCCESS = 'PROJECT_CATEGORY_LIST_SUCCESS';
export const PROJECT_CATEGORY_LIST_FAIL = 'PROJECT_CATEGORY_LIST_FAIL';

export const PROJECT_STATUS_LIST_REQUEST = 'PROJECT_STATUS_LIST_REQUEST';
export const PROJECT_STATUS_LIST_SUCCESS = 'PROJECT_STATUS_LIST_SUCCESS';
export const PROJECT_STATUS_LIST_FAIL = 'PROJECT_STATUS_LIST_FAIL';

export const AMENITY_LIST_REQUEST = 'AMENITY_LIST_REQUEST';
export const AMENITY_LIST_SUCCESS = 'AMENITY_LIST_SUCCESS';
export const AMENITY_LIST_FAIL = 'AMENITY_LIST_FAIL';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_COMPLETE = 'PROJECT_CREATE_COMPLETE';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';

export const EQUITY_INVESTMENT_LIST_REQUEST = 'EQUITY_INVESTMENT_LIST_REQUEST';
export const EQUITY_INVESTMENT_LIST_SUCCESS = 'EQUITY_INVESTMENT_LIST_SUCCESS';
export const EQUITY_INVESTMENT_LIST_FAIL = 'EQUITY_INVESTMENT_LIST_FAIL';

export const PROJECTS_STAT_SUCCESS = 'PROJECTS_STAT_SUCCESS';
export const PROJECTS_STAT_REQUEST = 'PROJECTS_STAT_REQUEST';
export const PROJECTS_STAT_FAIL = 'PROJECTS_STAT_FAIL';