
export const PROJECT_STATUS_LIST_REQUEST = 'PROJECT_STATUS_LIST_REQUEST';
export const PROJECT_STATUS_LIST_SUCCESS = 'PROJECT_STATUS_LIST_SUCCESS';
export const PROJECT_STATUS_LIST_FAIL = 'PROJECT_STATUS_LIST_FAIL';

export const PROJECT_STATUS_DETAIL_REQUEST = 'PROJECT_STATUS_DETAIL_REQUEST';
export const PROJECT_STATUS_DETAIL_SUCCESS = 'PROJECT_STATUS_DETAIL_SUCCESS';
export const PROJECT_STATUS_DETAIL_FAIL = 'PROJECT_STATUS_DETAIL_FAIL';
export const PROJECT_STATUS_DETAIL_RESET = 'PROJECT_STATUS_DETAIL_RESET';

export const PROJECT_STATUS_CREATE_REQUEST = 'PROJECT_STATUS_CREATE_REQUEST';
export const PROJECT_STATUS_CREATE_SUCCESS = 'PROJECT_STATUS_CREATE_SUCCESS';
export const PROJECT_STATUS_CREATE_COMPLETE = 'PROJECT_STATUS_CREATE_COMPLETE';
export const PROJECT_STATUS_CREATE_FAIL = 'PROJECT_STATUS_CREATE_FAIL';






export const LAND_TITLE_LIST_REQUEST = 'LAND_TITLE_LIST_REQUEST';
export const LAND_TITLE_LIST_SUCCESS = 'LAND_TITLE_LIST_SUCCESS';
export const LAND_TITLE_LIST_FAIL = 'LAND_TITLE_LIST_FAIL';

export const LAND_TITLE_DETAIL_REQUEST = 'LAND_TITLE_DETAIL_REQUEST';
export const LAND_TITLE_DETAIL_SUCCESS = 'LAND_TITLE_DETAIL_SUCCESS';
export const LAND_TITLE_DETAIL_FAIL = 'LAND_TITLE_DETAIL_FAIL';
export const LAND_TITLE_DETAIL_RESET = 'LAND_TITLE_DETAIL_RESET';

export const LAND_TITLE_CREATE_REQUEST = 'LAND_TITLE_CREATE_REQUEST';
export const LAND_TITLE_CREATE_SUCCESS = 'LAND_TITLE_CREATE_SUCCESS';
export const LAND_TITLE_CREATE_COMPLETE = 'LAND_TITLE_CREATE_COMPLETE';
export const LAND_TITLE_CREATE_FAIL = 'LAND_TITLE_CREATE_FAIL';




export const AMENITIES_LIST_REQUEST = 'AMENITIES_LIST_REQUEST';
export const AMENITIES_LIST_SUCCESS = 'AMENITIES_LIST_SUCCESS';
export const AMENITIES_LIST_FAIL = 'AMENITIES_LIST_FAIL';

export const AMENITIES_DETAIL_REQUEST = 'AMENITIES_DETAIL_REQUEST';
export const AMENITIES_DETAIL_SUCCESS = 'AMENITIES_DETAIL_SUCCESS';
export const AMENITIES_DETAIL_FAIL = 'AMENITIES_DETAIL_FAIL';
export const AMENITIES_DETAIL_RESET = 'AMENITIES_DETAIL_RESET';


export const AMENITIES_CREATE_REQUEST = 'AMENITIES_CREATE_REQUEST';
export const AMENITIES_CREATE_SUCCESS = 'AMENITIES_CREATE_SUCCESS';
export const AMENITIES_CREATE_COMPLETE = 'AMENITIES_CREATE_COMPLETE';
export const AMENITIES_CREATE_FAIL = 'AMENITIES_CREATE_FAIL';





export const BUILDING_TYPE_LIST_REQUEST = 'BUILDING_TYPE_LIST_REQUEST';
export const BUILDING_TYPE_LIST_SUCCESS = 'BUILDING_TYPE_LIST_SUCCESS';
export const BUILDING_TYPE_LIST_FAIL = 'BUILDING_TYPE_LIST_FAIL';
// export const BUILDING_TYPE_LIST_RESET = 'BUILDING_TYPE_LIST_RESET';


export const BUILDING_TYPE_DETAIL_REQUEST = 'BUILDING_TYPE_DETAIL_REQUEST';
export const BUILDING_TYPE_DETAIL_SUCCESS = 'BUILDING_TYPE_DETAIL_SUCCESS';
export const BUILDING_TYPE_DETAIL_FAIL = 'BUILDING_TYPE_DETAIL_FAIL';
export const BUILDING_TYPE_DETAIL_RESET = 'BUILDING_TYPE_DETAIL_RESET';

export const BUILDING_TYPE_CREATE_REQUEST = 'BUILDING_TYPE_CREATE_REQUEST';
export const BUILDING_TYPE_CREATE_SUCCESS = 'BUILDING_TYPE_CREATE_SUCCESS';
export const BUILDING_TYPE_CREATE_COMPLETE = 'BUILDING_TYPE_CREATE_COMPLETE';
export const BUILDING_TYPE_CREATE_FAIL = 'BUILDING_TYPE_CREATE_FAIL';






export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_DETAIL_REQUEST = 'CATEGORY_DETAIL_REQUEST';
export const CATEGORY_DETAIL_SUCCESS = 'CATEGORY_DETAIL_SUCCESS';
export const CATEGORY_DETAIL_FAIL = 'CATEGORY_DETAIL_FAIL';
export const CATEGORY_DETAIL_RESET = 'CATEGORY_DETAIL_RESET';

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_COMPLETE = 'CATEGORY_CREATE_COMPLETE';
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL';