export const TRANSACTIONS_LIST_REQUEST = 'TRANSACTIONS_LIST_REQUEST';
export const TRANSACTIONS_LIST_SUCCESS = 'TRANSACTIONS_LIST_SUCCESS';
export const TRANSACTIONS_LIST_FAIL = 'TRANSACTIONS_LIST_FAIL';

export const TRANSACTIONS_DETAIL_REQUEST = 'TRANSACTIONS_DETAIL_REQUEST';
export const TRANSACTIONS_DETAIL_SUCCESS = 'TRANSACTIONS_DETAIL_SUCCESS';
export const TRANSACTIONS_DETAIL_FAIL = 'TRANSACTIONS_DETAIL_FAIL';
export const TRANSACTIONS_DETAIL_RESET = 'TRANSACTIONS_DETAIL_RESET';

