export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_REFRESH_TOKEN_REQUEST = 'ADMIN_REFRESH_TOKEN_REQUEST';
export const ADMIN_REFRESH_TOKEN_SUCCESS = 'ADMIN_REFRESH_TOKEN_SUCCESS';
export const ADMIN_REFRESH_TOKEN_FAIL = 'ADMIN_REFRESH_TOKEN_FAIL';


export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';


export const SUPER_ADMIN_CREATE_REQUEST = 'SUPER_ADMIN_CREATE_REQUEST';
export const SUPER_ADMIN_CREATE_SUCCESS = 'SUPER_ADMIN_CREATE_SUCCESS';
export const SUPER_ADMIN_CREATE_COMPLETE = 'SUPER_ADMIN_CREATE_COMPLETE';
export const SUPER_ADMIN_CREATE_FAIL = 'SUPER_ADMIN_CREATE_FAIL';

export const ADMIN_CREATE_REQUEST = 'ADMIN_CREATE_REQUEST';
export const ADMIN_CREATE_SUCCESS = 'ADMIN_CREATE_SUCCESS';
export const ADMIN_CREATE_COMPLETE = 'ADMIN_CREATE_COMPLETE';
export const ADMIN_CREATE_FAIL = 'ADMIN_CREATE_FAIL';


export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCESS';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';


export const SUPER_ADMIN_LIST_REQUEST = 'SUPER_ADMIN_LIST_REQUEST';
export const SUPER_ADMIN_LIST_SUCCESS = 'SUPER_ADMIN_LIST_SUCCESS';
export const SUPER_ADMIN_LIST_FAIL = 'SUPER_ADMIN_LIST_FAIL';


export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST';
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAIL = 'COUNTRY_LIST_FAIL';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_COMPLETE = 'PROJECT_CREATE_COMPLETE';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';


export const VERIFICATION_ID_LIST_REQUEST = 'VERIFICATION_ID_LIST_REQUEST';
export const VERIFICATION_ID_LIST_SUCCESS = 'VERIFICATION_ID_LIST_SUCCESS';
export const VERIFICATION_ID_LIST_FAIL = 'VERIFICATION_ID_LIST_FAIL';

export const VERIFICATION_ID_DETAIL_REQUEST = 'VERIFICATION_ID_DETAIL_REQUEST';
export const VERIFICATION_ID_DETAIL_SUCCESS = 'VERIFICATION_ID_DETAIL_SUCCESS';
export const VERIFICATION_ID_DETAIL_FAIL = 'VERIFICATION_ID_DETAIL_FAIL';

export const VERIFICATION_ID_DETAIL_CLEAR = 'VERIFICATION_ID_DETAIL_CLEAR';


export const VERIFICATION_ID_VERIFY_REQUEST = 'VERIFICATION_ID_VERIFY_REQUEST';
export const VERIFICATION_ID_VERIFY_SUCCESS = 'VERIFICATION_ID_VERIFY_SUCCESS';
export const VERIFICATION_ID_VERIFY_COMPLETE = 'VERIFICATION_ID_VERIFY_COMPLETE';
export const VERIFICATION_ID_VERIFY_FAIL = 'VERIFICATION_ID_VERIFY_FAIL';

export const INVESTORS_LIST = 'INVESTORS_LIST';

